# Generated by Django 5.2.12 on 2026-03-03 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_settings',
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('category', models.TextField(default='general')),
                ('enabled', models.BooleanField(default=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_tools',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('base_url', models.TextField()),
                ('auth_type', models.TextField(choices=[('password_only', 'Password Only'), ('username_password', 'Username + Password'), ('none', 'None')], default='password_only')),
                ('credentials', models.JSONField(default=dict)),
                ('launcher_config', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'environments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running')),
                ('trigger_type', models.TextField(default='manual')),
                ('config', models.JSONField(default=dict)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('subject', models.TextField(blank=True, null=True)),
                ('grade', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('form_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.environment')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('numeric_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.TextField(unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('tier', models.TextField(blank=True, null=True)),
                ('languages', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, db_column='assessment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.assessment')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['numeric_id'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.TextField()),
                ('status', models.TextField(default='pending')),
                ('issues_found', models.BooleanField(default=False)),
                ('issues', models.JSONField(default=list)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('model_used', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item', to_field='item_id')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='core.testrun')),
            ],
            options={
                'db_table': 'ai_analyses',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dismissed', 'Dismissed'), ('bug_filed', 'Bug Filed')], default='pending')),
                ('notes', models.TextField(blank=True, null=True)),
                ('bug_url', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.aianalysis')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser', models.TextField()),
                ('device_profile', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('screenshot_path', models.TextField(blank=True, null=True)),
                ('diff_path', models.TextField(blank=True, null=True)),
                ('diff_ratio', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item', to_field='item_id')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testrun')),
            ],
            options={
                'db_table': 'test_results',
            },
        ),
        migrations.CreateModel(
            name='TestRunScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_path', models.TextField()),
                ('status', models.TextField(choices=[('queued', 'Queued'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='queued')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_log', models.TextField(blank=True, null=True)),
                ('trace_path', models.TextField(blank=True, null=True)),
                ('video_path', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_results', to='core.testrun')),
            ],
            options={
                'db_table': 'test_run_scripts',
                'ordering': ['script_path'],
            },
        ),
        migrations.CreateModel(
            name='TestScript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('script_path', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, db_column='assessment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assessment')),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item', to_field='item_id')),
            ],
            options={
                'db_table': 'test_scripts',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('browser_profiles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suites', to='core.environment')),
            ],
            options={
                'db_table': 'test_suites',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='testrun',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='core.testsuite'),
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser', models.TextField()),
                ('device_profile', models.TextField()),
                ('version', models.TextField()),
                ('screenshot_path', models.TextField()),
                ('approved_by', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='core.item', to_field='item_id')),
            ],
            options={
                'db_table': 'baselines',
                'unique_together': {('item', 'browser', 'device_profile', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TestSuiteScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_path', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.testsuite')),
            ],
            options={
                'db_table': 'test_suite_scripts',
                'unique_together': {('suite', 'script_path')},
            },
        ),
        migrations.CreateModel(
            name='UserEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='core.environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_environments',
                'unique_together': {('user', 'environment')},
            },
        ),
    ]
