# Generated by Django 5.2.12 on 2026-03-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_numeric_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={'ordering': ['-queued_at']},
        ),
        migrations.AddField(
            model_name='testrun',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
