# Generated by Django 5.2.12 on 2026-03-06 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('file_path', models.TextField()),
                ('project_name', models.TextField(default='chrome-desktop')),
                ('flagged', models.BooleanField(default=False)),
                ('flag_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.testrun')),
                ('run_script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='core.testrunscript')),
            ],
            options={
                'db_table': 'run_screenshots',
                'ordering': ['name'],
            },
        ),
    ]
