# Generated by Django 5.2.12 on 2026-03-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_run_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscript',
            name='ai_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
