# Generated by Django 5.2.12 on 2026-03-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testscript_chat_and_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscript',
            name='browser',
            field=models.TextField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit (Safari)')], default='chromium'),
        ),
        migrations.AddField(
            model_name='testscript',
            name='viewport',
            field=models.TextField(choices=[('1920x1080', '1920 x 1080 (Full HD)'), ('1280x720', '1280 x 720 (HD)'), ('1366x768', '1366 x 768 (Laptop)'), ('1024x768', '1024 x 768 (Tablet Landscape)'), ('768x1024', '768 x 1024 (Tablet Portrait)'), ('375x812', '375 x 812 (Mobile)')], default='1920x1080'),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='test_type',
            field=models.TextField(choices=[('functional', 'Functional'), ('visual_regression', 'Visual Regression'), ('ai_content', 'AI Content Analysis'), ('ai_visual', 'AI Visual Analysis'), ('qc_checklist', 'QC Checklist')], default='functional'),
        ),
    ]
