# Generated by Django 5.2.12 on 2026-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testscript_browser_viewport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsuitescript',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testrunscript',
            name='browser',
            field=models.TextField(default='chromium'),
        ),
        migrations.AddField(
            model_name='testrunscript',
            name='viewport',
            field=models.TextField(default='1920x1080'),
        ),
        migrations.AddField(
            model_name='testsuitescript',
            name='browser',
            field=models.TextField(default='chromium'),
        ),
        migrations.AddField(
            model_name='testsuitescript',
            name='viewport',
            field=models.TextField(default='1920x1080'),
        ),
        migrations.AlterUniqueTogether(
            name='testsuitescript',
            unique_together={('suite', 'script_path', 'browser', 'viewport')},
        ),
    ]
