# Generated by Django 5.2.12 on 2026-03-14 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_test_script_baselines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScriptArchive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_id', models.IntegerField()),
                ('script_path', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('test_type', models.TextField(default='functional')),
                ('ai_config', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(default=list)),
                ('category', models.TextField(blank=True, null=True)),
                ('test_summary', models.TextField(blank=True, null=True)),
                ('browser', models.TextField(default='chromium')),
                ('viewport', models.TextField(default='1920x1080')),
                ('file_content', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, db_column='archived_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, db_column='assessment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assessment')),
                ('environment', models.ForeignKey(blank=True, db_column='environment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.environment')),
                ('item', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item', to_field='item_id')),
            ],
            options={
                'db_table': 'test_script_archives',
                'ordering': ['-archived_at'],
            },
        ),
    ]
