# Generated by Django 5.2.12 on 2026-03-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_test_script_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='screenshot_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
