# Generated by Django 5.2.12 on 2026-03-15 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_apiclient_apiclientlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bug_url',
        ),
        migrations.AddField(
            model_name='review',
            name='screenshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.runscreenshot'),
        ),
        migrations.AddField(
            model_name='review',
            name='source_type',
            field=models.TextField(choices=[('ai_analysis', 'AI Analysis'), ('screenshot', 'Screenshot Flag')], default='ai_analysis'),
        ),
        migrations.AlterField(
            model_name='review',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.aianalysis'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('issue', 'Issue'), ('suppressed', 'Suppressed')], default='pending'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE reviews SET status = 'issue' WHERE status IN ('approved', 'bug_filed');
                UPDATE reviews SET status = 'suppressed' WHERE status = 'dismissed';
            """,
            reverse_sql="""
                UPDATE reviews SET status = 'approved' WHERE status = 'issue';
                UPDATE reviews SET status = 'dismissed' WHERE status = 'suppressed';
            """,
        ),
        migrations.CreateModel(
            name='ReviewSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screenshot_name', models.TextField()),
                ('script_path', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='core.environment')),
                ('suppressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_suppressions',
                'ordering': ['-created_at'],
                'unique_together': {('screenshot_name', 'script_path', 'environment')},
            },
        ),
    ]
