# Generated by Django 5.2.12 on 2026-03-15 02:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_review_bug_url_review_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdataset',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_data_sets', to='core.item', to_field='item_id'),
        ),
        migrations.CreateModel(
            name='TestScriptDataSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_links', to='core.testdataset')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_set_links', to='core.testscript')),
            ],
            options={
                'db_table': 'test_script_data_sets',
                'unique_together': {('script', 'data_set')},
            },
        ),
    ]
