# Generated by Django 5.2.12 on 2026-03-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_testdataset_item_testscriptdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
