# Generated by Django 5.2.12 on 2026-03-15 19:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aianalysis_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('provider_type', models.TextField(choices=[('anthropic', 'Anthropic / Azure AI Foundry'), ('azure_openai', 'Azure OpenAI'), ('openai_compat', 'OpenAI / OpenRouter / Ollama')])),
                ('api_key', models.TextField(blank=True, default='')),
                ('model', models.TextField(blank=True, default='')),
                ('base_url', models.TextField(blank=True, default='')),
                ('deployment_id', models.TextField(blank=True, default='')),
                ('api_version', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_providers',
                'ordering': ['name'],
            },
        ),
    ]
