# Generated by Django 5.2.12 on 2026-03-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_level_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('issue', 'Issue'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='pending'),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='test_type',
            field=models.TextField(choices=[('functional', 'Functional'), ('visual_regression', 'Visual Regression'), ('qc_checklist', 'Item Types QC')], default='functional'),
        ),
    ]
